from typing import Protocol

from recall_rover.memory.models import Pose


class Robot(Protocol):
    moving: bool

    async def get_pose(self) -> Pose: ...
    async def get_camera_frame(self): ...
    async def navigate_to(self, pose: Pose, speed: float): ...
    async def rotate(self, angle: float, speed: float): ...
    async def stop(self): ...
    async def get_health(self) -> dict: ...
